services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/usr/src/app/data # Named volume for SQLite
      - /app/logs # Anonymous volume for logs

volumes:
  sqlite_data: # Define the named volume
